In [1]:
import pandas as pd

In [2]:
play_df = pd.read_csv("data/plays.csv")

In [3]:
week_1_df = pd.read_csv("data/week1.csv")

In [4]:
games_df = pd.read_csv("data/games.csv")

In [5]:
week_1_df.shape

(986022, 19)

In [6]:
play_df.columns

Index(['gameId', 'playId', 'playDescription', 'quarter', 'down', 'yardsToGo',
       'possessionTeam', 'playType', 'yardlineSide', 'yardlineNumber',
       'offenseFormation', 'personnelO', 'defendersInTheBox',
       'numberOfPassRushers', 'personnelD', 'typeDropback',
       'preSnapVisitorScore', 'preSnapHomeScore', 'gameClock',
       'absoluteYardlineNumber', 'penaltyCodes', 'penaltyJerseyNumbers',
       'passResult', 'offensePlayResult', 'playResult', 'epa',
       'isDefensivePI'],
      dtype='object')

In [7]:
# find DPI (defensive pass interference) and which game and play id
dpi_example = play_df[play_df.penaltyCodes == 'DPI'].iloc[0]

In [8]:
dpi_example

gameId                                                           2018092700
playId                                                                 1268
playDescription           (8:13) K.Cousins pass deep right to A.Robinson...
quarter                                                                   2
down                                                                      1
yardsToGo                                                                10
possessionTeam                                                          MIN
playType                                                     play_type_pass
yardlineSide                                                             LA
yardlineNumber                                                           17
offenseFormation                                                 SINGLEBACK
personnelO                                                 1 RB, 2 TE, 2 WR
defendersInTheBox                                                         7
numberOfPassRushers                                                       5
personnelD                                                 3 DL, 4 LB, 4 DB
typeDropback                                         SCRAMBLE_ROLLOUT_RIGHT
preSnapVisitorScore                                                      10
preSnapHomeScore                                                         14
gameClock                                                          08:13:00
absoluteYardlineNumber                                                   27
penaltyCodes                                                            DPI
penaltyJerseyNumbers                                                  LA 37
passResult                                                                C
offensePlayResult                                                        17
playResult                                                               17
epa                                                                 2.31185
isDefensivePI                                                          True
Name: 3455, dtype: object

In [9]:
play_df[play_df.penaltyCodes == 'DPI'].playType.value_counts()

play_type_unknown    221
play_type_pass        21
Name: playType, dtype: int64

In [21]:
games_df.columns

Index(['gameId', 'gameDate', 'gameTimeEastern', 'homeTeamAbbr',
       'visitorTeamAbbr', 'week'],
      dtype='object')

In [24]:
games_df.shape

(253, 6)

In [25]:
game_example = games_df[games_df.gameId == 2018092700]
game_example

        gameId    gameDate gameTimeEastern homeTeamAbbr visitorTeamAbbr  week
45  2018092700  09/27/2018        20:20:00           LA             MIN     4

In [26]:
week_4_df = pd.read_csv("data/week4.csv")

In [28]:
match_data_example_dpi = week_4_df[week_4_df.playId == 1268]
match_data_example_dpi

,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,gameId,playId,playDirection,route
28669,2018-09-28T01:10:36.500Z,26.05,12.31,0.13,0.04,0.02,88.95,64.01,None,1037374.0,Sam Shields,37.0,CB,1,home,2018092700,1268,left,NaN
28670,2018-09-28T01:10:36.500Z,28.13,12.22,0.01,0.01,0.01,288.94,48.82,None,2495331.0,Aldrick Robinson,17.0,WR,1,away,2018092700,1268,left,CROSS
28671,2018-09-28T01:10:36.500Z,27.85,29.66,0.00,0.00,0.00,269.47,243.71,None,2495438.0,Kyle Rudolph,82.0,TE,1,away,2018092700,1268,left,CORNER
28672,2018-09-28T01:10:36.500Z,28.46,23.68,0.00,0.00,0.00,253.11,183.72,None,2532820.0,Kirk Cousins,8.0,QB,1,away,2018092700,1268,left,NaN
28673,2018-09-28T01:10:36.500Z,29.54,32.16,0.01,0.01,0.01,252.05,346.32,None,2541785.0,Adam Thielen,19.0,WR,1,away,2018092700,1268,left,OUT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29729,2018-09-28T01:10:43.500Z,27.30,15.53,3.45,0.61,0.34,326.23,327.61,None,2557991.0,Dalvin Cook,33.0,RB,71,away,2018092700,1268,left,FLAT
29730,2018-09-28T01:10:43.500Z,4.04,44.85,7.91,1.91,0.80,348.50,327.05,None,2558183.0,John Johnson,43.0,SS,71,home,2018092700,1268,left,NaN
29731,2018-09-28T01:10:43.500Z,34.00,44.29,2.90,2.04,0.30,321.07,325.81,None,2558830.0,Samson Ebukam,50.0,OLB,71,home,2018092700,1268,left,NaN
29732,2018-09-28T01:10:43.500Z,19.19,43.83,4.90,1.33,0.50,320.44,331.73,None,2561027.0,Tyler Conklin,83.0,TE,71,away,2018092700,1268,left,CROSS
29733,2018-09-28T01:10:43.500Z,2.08,43.82,6.46,1.14,0.65,NaN,NaN,None,NaN,Football,NaN,NaN,71,football,2018092700,1268,left,NaN

In [29]:
match_data_example_dpi.shape

(1065, 19)

In [36]:
match_data_example_dpi = match_data_example_dpi.sort_values(by='frameId')
match_data_example_dpi[:16]

,time,x,y,s,a,dis,o,dir,event,nflId,displayName,jerseyNumber,position,frameId,team,gameId,playId,playDirection,route
28669,2018-09-28T01:10:36.500Z,26.05,12.31,0.13,0.04,0.02,88.95,64.01,None,1037374.0,Sam Shields,37.0,CB,1,home,2018092700,1268,left,NaN
28672,2018-09-28T01:10:36.500Z,28.46,23.68,0.00,0.00,0.00,253.11,183.72,None,2532820.0,Kirk Cousins,8.0,QB,1,away,2018092700,1268,left,NaN
28673,2018-09-28T01:10:36.500Z,29.54,32.16,0.01,0.01,0.01,252.05,346.32,None,2541785.0,Adam Thielen,19.0,WR,1,away,2018092700,1268,left,OUT
28676,2018-09-28T01:10:36.500Z,19.99,33.31,0.40,0.25,0.04,102.99,195.58,None,2552488.0,Marcus Peters,22.0,CB,1,home,2018092700,1268,left,NaN
28670,2018-09-28T01:10:36.500Z,28.13,12.22,0.01,0.01,0.01,288.94,48.82,None,2495331.0,Aldrick Robinson,17.0,WR,1,away,2018092700,1268,left,CROSS
28674,2018-09-28T01:10:36.500Z,20.22,20.99,3.65,2.48,0.38,123.57,173.46,None,2543492.0,Lamarcus Joyner,20.0,FS,1,home,2018092700,1268,left,NaN
28675,2018-09-28T01:10:36.500Z,23.50,22.80,0.01,0.01,0.01,87.02,216.62,None,2552320.0,Ramik Wilson,52.0,ILB,1,home,2018092700,1268,left,NaN
28671,2018-09-28T01:10:36.500Z,27.85,29.66,0.00,0.00,0.00,269.47,243.71,None,2495438.0,Kyle Rudolph,82.0,TE,1,away,2018092700,1268,left,CORNER
28677,2018-09-28T01:10:36.500Z,25.65,18.22,0.33,0.89,0.03,78.90,129.83,None,2553722.0,Matt Longacre,96.0,OLB,1,home,2018092700,1268,left,NaN
28678,2018-09-28T01:10:36.500Z,24.59,27.91,0.04,0.04,0.01,96.14,79.05,None,2556593.0,Cory Littleton,58.0,ILB,1,home,2018092700,1268,left,NaN
28682,2018-09-28T01:10:36.500Z,29.50,17.37,1.87,5.24,0.20,285.19,206.82,None,2561027.0,Tyler Conklin,83.0,TE,1,away,2018092700,1268,left,CROSS
28683,2018-09-28T01:10:36.500Z,26.83,23.77,0.00,0.00,0.00,NaN,NaN,None,NaN,Football,NaN,NaN,1,football,2018092700,1268,left,NaN
28679,2018-09-28T01:10:36.500Z,35.18,24.11,0.00,0.00,0.00,248.53,31.42,None,2557991.0,Dalvin Cook,33.0,RB,1,away,2018092700,1268,left,FLAT
28680,2018-09-28T01:10:36.500Z,23.17,30.14,0.15,0.24,0.02,109.03,356.37,None,2558183.0,John Johnson,43.0,SS,1,home,2018092700,1268,left,NaN
28681,2018-09-28T01:10:36.500Z,25.83,30.46,0.02,0.02,0.00,114.96,157.29,None,2558830.0,Samson Ebukam,50.0,OLB,1,home,2018092700,1268,left,NaN
28686,2018-09-28T01:10:36.599Z,27.85,29.66,0.00,0.00,0.00,269.47,246.02,None,2495438.0,Kyle Rudolph,82.0,TE,2,away,2018092700,1268,left,CORNER